# Generated by Django 5.2.11 on 2026-02-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Instagram ID"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Подпись"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Тип медиа"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="URL медиа"
                    ),
                ),
                (
                    "permalink",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="Ссылка"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="Дата создания в Instagram"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_comment_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Instagram Comment ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="instagram.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
        ),
    ]
